#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"
ynh_systemctl --service=$app-tasks --action="stop"
ynh_systemctl --service=$app-wss --action="stop"

secret=$(ynh_app_setting_get --key=secret)
timezone=$(timedatectl show --value --property=Timezone)
auth_secret=$(ynh_app_setting_get --key=auth_secret)
secret_encryption_key=$(ynh_app_setting_get --key=secret_encryption_key)
cron_job_api_key=$(ynh_app_setting_get --key=cron_job_api_key)
redis_db=$(ynh_app_setting_get --key=redis_db)

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app-tasks --action="start"  --timeout=600
ynh_systemctl --service=$app-wss --action="start"  --timeout=600
ynh_systemctl --service=$app --action="start"  --timeout=600

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
