#!/bin/bash

source /usr/share/yunohost/helpers

secret=$(ynh_string_random --length=24)
timezone=$(timedatectl show --value --property=Timezone)
auth_secret=$(ynh_string_random --length=32)
secret_encryption_key=$(ynh_string_random --length=64 --filter= 'a-f0-9')
cron_job_api_key=$(ynh_string_random --length=32)

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install
npm install corepack

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Customizable browser's home page" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# INSTALL HOMARR
#=================================================
ynh_script_progression "Building the app..."

pushd $install_dir
    ynh_hide_warnings corepack enable
    ynh_hide_warnings npm install -g corepack@latest
    ynh_hide_warnings ynh_exec_as_app corepack prepare pnpm@9 --activate

    chown -R $app:$app $install_dir
	ynh_hide_warnings ynh_exec_as_app pnpm install
	ynh_hide_warnings pnpm run db:migration:sqlite:run
	ynh_hide_warnings NODE_OPTIONS="--max-old-space-size=3000" pnpm build
    mkdir build
    cp $install_dir/node_modules/better-sqlite3/build/Release/better_sqlite3.node $install_dir/build/better_sqlite3.node
    ynh_hide_warnings ynh_exec_as_app pnpm build
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
