#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

if ynh_hide_warnings yunohost service status $app-tasks >/dev/null; then
	yunohost service remove $app-tasks 
fi

if ynh_hide_warnings yunohost service status $app-wss >/dev/null; then
	yunohost service remove $app-wss
fi

ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_redis_remove_db $redis_db

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
