#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="/var/log/$app/$app.log"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=auth_secret --value="$(ynh_string_random --length=32)"
ynh_app_setting_set_default --key=secret_encryption_key --value="$(ynh_string_random --length=64 --filter="0-9a-f")"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env /database"

#=================================================
# UPGRADE DEPENDENCIES
#=================================================
ynh_script_progression "Upgrading dependencies..."

ynh_nodejs_install

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
yunohost service add "$app" --description="Customizable browser's home page" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# INSTALL HOMARR
#=================================================
ynh_script_progression "Building the app..."

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app mkdir -p "$install_dir/database/"
	ynh_hide_warnings corepack enable
	ynh_hide_warnings corepack prepare pnpm@latest --activate
	ynh_hide_warnings ynh_exec_as_app pnpm install --recursive --frozen-lockfile
	ynh_hide_warnings ynh_exec_as_app pnpm db:migration:sqlite:run
	ynh_hide_warnings ynh_exec_as_app NODE_ENV=production NODE_OPTIONS="--max-old-space-size=4096" pnpm build
	ynh_hide_warnings ynh_exec_as_app mkdir -p "$install_dir/build/"
	ynh_hide_warnings ynh_exec_as_app cp -a "$install_dir/node_modules/better-sqlite3/build/Release/better_sqlite3.node" "$install_dir/build/better_sqlite3.node"
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --wait_until="Ready in" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
